import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
    container: {
        width: '100%',
        maxWidth: '800px',
        height: '95vh',
        backgroundColor: 'var(--surface-color)',
        borderRadius: '16px',
        border: '1px solid var(--border-color)',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
    },
    header: {
        padding: '1rem 1.5rem',
        borderBottom: '1px solid var(--border-color)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexShrink: 0,
    },
    rating: {
        fontFamily: 'var(--font-display)',
        fontSize: '1.75rem',
        color: 'var(--primary-color)',
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    logoutButton: {
        background: 'none',
        border: '1px solid var(--border-color)',
        color: 'var(--text-secondary)',
        padding: '0.5rem 1rem',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    mainContent: {
        flexGrow: 1,
        padding: '1.5rem',
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
    },
    gameScreen: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
    },
    questionCard: {
        backgroundColor: 'rgba(0,0,0,0.2)',
        padding: '1.5rem',
        borderRadius: '12px',
        border: '1px solid var(--border-color)',
    },
    questionMeta: {
        display: 'flex',
        justifyContent: 'space-between',
        marginBottom: '1rem',
        fontSize: '0.9rem',
        color: 'var(--text-secondary)',
    },
    questionText: {
        fontSize: '1.2rem',
        lineHeight: '1.6',
        marginBottom: '1.5rem',
    },
    textarea: {
        width: '100%',
        minHeight: '150px',
        backgroundColor: '#121212',
        border: '1px solid var(--border-color)',
        borderRadius: '8px',
        padding: '1rem',
        color: 'var(--text-primary)',
        fontFamily: 'var(--font-main)',
        fontSize: '1rem',
        resize: 'vertical',
    },
    submitButton: {
        width: '100%',
        padding: '1rem',
        marginTop: '1rem',
        border: 'none',
        borderRadius: '8px',
        backgroundColor: 'var(--primary-color)',
        color: '#121212',
        fontSize: '1.1rem',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'background-color 0.2s ease',
    },
    statsFooter: {
        padding: '1rem 1.5rem',
        borderTop: '1px solid var(--border-color)',
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
        gap: '1rem',
        flexShrink: 0,
    },
    categoryStat: {
        textAlign: 'center',
    },
    feedbackOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(18, 18, 18, 0.95)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '2rem',
        zIndex: 100,
        overflowY: 'auto',
    },
    feedbackContent: {
        width: '100%',
        maxWidth: '700px',
        textAlign: 'center',
    },
    overallScore: {
        fontSize: '5rem',
        fontFamily: 'var(--font-display)',
        color: 'var(--primary-color)',
        marginBottom: '1rem',
    },
    evaluationSummary: {
        color: 'var(--text-secondary)',
        marginBottom: '2rem',
        textAlign: 'left',
        lineHeight: 1.5,
        maxWidth: '100%',
    },
    summarySection: {
        marginBottom: '1rem'
    },
    summaryTitle: {
        fontSize: '1.1rem',
        marginBottom: '0.75rem',
        fontWeight: '600',
        fontFamily: 'var(--font-display)'
    },
    summaryList: {
        listStyle: 'none',
        paddingLeft: '0',
        margin: 0,
    },
    summaryItem: {
        position: 'relative',
        paddingLeft: '1.5rem',
        marginBottom: '0.5rem',
    },
    categoryScores: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
        marginBottom: '2rem',
        textAlign: 'left',
        backgroundColor: 'rgba(0,0,0,0.2)',
        padding: '1rem',
        borderRadius: '8px',
        border: '1px solid var(--border-color)',
    },
    userSetup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
        width: '100%',
        maxWidth: '550px',
        padding: '2rem',
        backgroundColor: 'var(--surface-color)',
        borderRadius: '16px',
        border: '1px solid var(--border-color)',
        boxSizing: 'border-box',
        overflow: 'hidden',
    },
    input: {
        width: '100%',
        padding: '1rem',
        backgroundColor: '#121212',
        border: '1px solid var(--border-color)',
        borderRadius: '8px',
        color: 'var(--text-primary)',
        fontSize: '1rem',
    },
    title: {
        fontFamily: 'var(--font-display)',
        fontSize: '2rem',
        textAlign: 'center',
        color: 'var(--primary-color)',
        marginBottom: '0.5rem',
    },
    subtitle: {
        textAlign: 'center',
        color: 'var(--text-secondary)',
        marginBottom: '1rem',
    },
    link: {
        color: 'var(--secondary-color)',
        textDecoration: 'none'
    },
    progressSummaryCard: {
      width: '100%',
      maxWidth: '500px',
      padding: '2rem',
      backgroundColor: 'var(--surface-color)',
      borderRadius: '16px',
      border: '1px solid var(--border-color)',
      textAlign: 'center'
    },
    progressCategoryList: {
      textAlign: 'left',
      margin: '2rem 0',
      display: 'flex',
      flexDirection: 'column',
      gap: '1rem',
    },
     secondaryButton: {
      background: 'none',
      border: '1px solid var(--border-color)',
      color: 'var(--text-secondary)',
      padding: '1rem',
      width: '100%',
      borderRadius: '8px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    },
    statsSummaryGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
        gap: '1rem',
        marginBottom: '1.5rem',
    },
    statsSummaryCard: {
        backgroundColor: 'rgba(0,0,0,0.2)',
        padding: '1.5rem',
        borderRadius: '12px',
        border: '1px solid var(--border-color)',
        textAlign: 'center',
    },
    chartCard: {
        backgroundColor: 'rgba(0,0,0,0.2)',
        padding: '2rem',
        borderRadius: '12px',
        border: '1px solid var(--border-color)',
        textAlign: 'center',
    },
    chartContainer: {
        display: 'flex',
        justifyContent: 'space-around',
        alignItems: 'flex-end',
        height: '250px',
        borderLeft: '1px solid var(--border-color)',
        borderBottom: '1px solid var(--border-color)',
        padding: '1rem 0 0 1rem',
    },
    chartBarWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        flex: 1,
        textAlign: 'center',
        height: '100%',
        justifyContent: 'flex-end',
    },
    chartBar: {
        width: '50%',
        maxWidth: '40px',
        borderRadius: '4px 4px 0 0',
        transition: 'height 0.5s ease-out',
        position: 'relative',
    },
    chartLabel: {
        marginTop: '0.75rem',
        fontSize: '0.75rem',
        color: 'var(--text-secondary)',
        height: '40px',
        wordBreak: 'break-word',
    },
    keypointGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '1rem'
    },
    keypointCard: {
        backgroundColor: 'rgba(0,0,0,0.2)',
        padding: '1.5rem',
        borderRadius: '12px',
        border: '1px solid var(--border-color)',
    },
    keypointList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
        marginTop: '1.5rem'
    },
    userDisplay: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
    },
    avatar: {
        width: '32px',
        height: '32px',
        borderRadius: '50%',
        border: '2px solid var(--border-color)',
    }
};